#!/bin/bash

echo "#!/bin/bash
sendmail() {
	echo $1 | mail -s 'Crontab backup' root;
	echo $1;
}

if [ ! -f /var/backups/crontab.bak ]; then
	sendmail 'Crontab backup has been corrupted';
	cp /etc/crontab /var/backups/crontab.bak;
elif [ \$(md5sum /var/backups/crontab.bak | cut -d' ' -f1) != \$(md5sum /etc/crontab | cut -d' ' -f1) ]; then
	sendmail 'Crontab has been modified';
	cp /etc/crontab /var/backups/crontab.bak;
else
	sendmail 'it ok';
fi" > /usr/local/bin/04

cp /etc/crontab /var/backups/crontab.bak;
/bin/bash /usr/local/bin/04

crontab -l > mycron 2> /dev/null
echo "* * * * * /bin/sh /usr/local/bin/04" >> mycron
crontab mycron
rm mycron
